name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    # - name: Build the c# code
    #   run: dotnet build
    
    # - name: Run the c# tests
    #   run: dotnet test

    # - name: Build the TypeScript code
    #   working-directory: ./DotnetTemplate.Web
    #   run: |
    #     npm install
    #     npm run build
   
    # - name: Run the TypeScript tests
    #   working-directory: ./DotnetTemplate.Web
    #   run: npm t

    # - name: Run the linter on the TypeScript code
    #   working-directory: ./DotnetTemplate.Web
    #   run: npm run lint

  # below to issue docker build and push commands 

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    
    - name: run the docker build
      run: docker build --tag m8 .

    - name: change tag 
      run: docker tag m8 cliver67/m8

    - name: Submit a docker push 
      run: docker push cliver67/m8
